Add functions for all Bit operations on Registers
ners/riscv-hs pull request #20
Opened 2023-04-30 16:21 UTC by kirschmet2

Also using fmap as an infix operator

2023-05-02 09:41 UTC, ners commented on src/Register.hs
> +implies x y = fromList (uncurry Bit.implies `fmap` zip (toList x) (toList y))
The operator form of `` `fmap` `` is `<$>`
Also consider using `fromList $` to remove one level of parentheses.

2023-05-02 09:43 UTC, ners requested changes
This pattern of
```haskell
fromList $ uncurry f <$> zip (toList x) (toList y)
```
can be generalised to a function called [`zipWith`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Prelude.html#v:zipWith).

```haskell
zipWith :: (a -> b -> c) -> FixedVector n a -> FixedVector n b -> FixedVector n c
```

Then `and` becomes:
```haskell
and = zipWith Bit.and
```

2023-05-07 12:42 UTC, kirschmet2 commented
Change implemented as requested, except for a change in the type of FixedVector.zipWith, `zipWith :: KnownNat n => (a -> b -> c) -> c -> FixedVector n a -> FixedVector n b -> FixedVector n c` to accomodate for toListWithDefault's variable, as I was unable to find a solution using tryFromList.

2023-05-10 12:25 UTC, ners approved these changes

2023-05-10 12:25 UTC, merged